baseurl = "http://issys16.info"
languageCode = "ja"
title = "issys16.info"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/issy-s16\">Shogo Ishikura</a> 2017"
disqusShortname = "http-issys16-info"
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/issy-s16"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/issy_s16"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
