# Site settings
baseurl = "https://issys16.info/blog/"

# HTML Language Code Reference, such as en, zh-cn
languageCode = "ja"
title = "issys16.info"
theme = "hugo-theme-cactus-plus"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
hasCJKLanguage = true

[params]
    name = "issys16.info"
    description = "issy_s16のweblog"
    bio = ""

    # Enter optionally your twitter account
    twitter = "issy_s16"
    enableRSS = false

    # Disqus comment
    disqusShortname = "http-issys16-info"
    # Disable disqus comments by set `enableDisqus = "false"`
    enableDisqus = true

    # Duoshuo comment
    duoshuoShortname = "your_duoshuo_short_name"
    # Disable duoshuo comments by set `enableDuoshuo = "false"`
    enableDuoshuo = false

    enableGithubIssuesTips = false

    # Enable googleAnalytics
    enableGoogleAnalytics = false

    # Add custom assets with their paths relative to the static folder
    customCSS = []
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = "home"
    about = "about"
    archive = "archive"
    subscribe = "subscribe"
    tags = "tags"

    # Pagination links
    olderPosts = "older"
    newerPosts = "newer"
    readMore = "read more"
    copyright = "&copy;2017 Shogo Ishikura"

    # Sharing options and author information in posts
    aboutAuthor = "I am so interesting."
    tweet = ""
    share = ""

    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "font-awesome"

    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""

# Add additional social link entries underneath
[social]
    facebook-square = "https://www.facebook.com/shogo.ishikura"
    twitter-square = "https://twitter.com/issy_s16"
    github-square = "https://github.com/issy-s16"
