version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: 'ls -l'
      # hugo install
      - run: 
          command: 'go get -u -v github.com/spf13/hugo'
      # hugo build
      - run:
          command: 'hugo -D'
      - run:
          command: 'ls -l'
  deploy:
    machine: true
    steps:
      # run rsync
      - run:
          command: 'pwd'
      - run:
          command: 'ls -l'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
