version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: ssh issys16.info
          command: 'ssh issy_s16@issys16.info ls -l'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
