version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: echo test
          command: 'echo test'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
