version: 2
jobs:
  build:
    working_directory: ~
    machine: true
    steps:
      - checkout
      # hugo install
      - run: 
          command: 'go get -u -v github.com/spf13/hugo'
      # hugo build
      - run:
          command: 'hugo -D'
      - save_cache:
          key: cache-{{ epoch }}
          paths:
            - ~
  deploy:
    working_directory: ~
    machine: true
    steps:
      - restore_cache:
          key: cache
      # run rsync
      - run:
          command: 'pwd'
      - run:
          command: 'ls -l'
      - run:
          command: 'rsync -ar public/ issy_s16@issys16.info:/home/issy_s16/tmp'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
