version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: 'ls -l'
      - run:
          command: 'pwd'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
