version 2
jobs:
  build:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
  test:
    machine: true
    steps:
      - run: echo test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
