version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
  pre-build:
    machine: true
    steps: 
      - run:
          command: 'ls -l'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - pre-build
